### ISSUE TITLE
ValueError in Installation example code

### ISSUE THREAD

**Issue by nlathia** [scikit-learn-contrib/project-template#12]
I have just installed the template (and am using scikit-learn v 0.16.1; **update** I get the same error with scikit-learn v 0.17.1). When I run the example code listed under "Installation and Usage:"

```
>>> from skltemplate import TemplateEstimator
>>> estimator = TemplateEstimator()
>>> estimator.fit(np.arange(10), np.arange(10))
```

I get the following ValueError:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "skltemplate/template.py", line 33, in fit
    X, y = check_X_y(X, y)
  File "/Library/Python/2.7/site-packages/sklearn/utils/validation.py", line 454, in check_X_y
    check_consistent_length(X, y)
  File "/Library/Python/2.7/site-packages/sklearn/utils/validation.py", line 174, in check_consistent_length
    "%s" % str(uniques))
ValueError: Found arrays with inconsistent numbers of samples: [ 1 10]
```

I am not very familiar with the checks that check_X_y is doing, but perhaps this is because X, in this case, is 1-dimensional? I checked this by running:

```
>>> estimator.fit(np.zeros([10, 10]), np.arange(10))
```

And no exception was raised.

**Comment by vighneshbirodkar** [comment]
Thanks for pointing this out.

Closed by #17
