### ISSUE TITLE
Documentation fails to build

### ISSUE THREAD

**Issue by dil12321** [scikit-learn-contrib/project-template#36]
Running `make html` results in

```Running Sphinx v1.7.4

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/usr/local/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 18, in <module>
    import sphinx_rtd_theme
ModuleNotFoundError: No module named 'sphinx_rtd_theme'

make: *** [html] Error 2
```

**Comment by glemaitre** [comment]
You need to pip install `sphinx_rtd_theme` from `pip`
