### ISSUE TITLE
python3.6.0 dateutil issue while make of pgadmin

### ISSUE THREAD

**Issue by Suniltech** [scikit-learn-contrib/project-template#37]
```pytb

make[1]: Entering directory `/usr/src/pgadmin4-3.0/docs/en_US'
Generating code-snippet.rst for some of the important classes...
sphinx-build -W -b html -d _build/doctrees   . _build/html
Running Sphinx v1.7.5

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/usr/local/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 27, in <module>
    import config
  File "/usr/src/pgadmin4-3.0/docs/en_US/../../web/config.py", line 29, in <module>
    from pgadmin.utils import env, IS_PY2, IS_WIN, fs_short_path
  File "/usr/src/pgadmin4-3.0/web/pgadmin/__init__.py", line 31, in <module>
    from pgadmin.utils import PgAdminModule, driver
  File "/usr/src/pgadmin4-3.0/web/pgadmin/utils/__init__.py", line 19, in <module>
    from .preferences import Preferences
  File "/usr/src/pgadmin4-3.0/web/pgadmin/utils/preferences.py", line 18, in <module>
    import dateutil.parser as dateutil_parser
ModuleNotFoundError: No module named 'dateutil'

make[1]: *** [html] Error 2
make[1]: Leaving directory `/usr/src/pgadmin4-3.0/docs/en_US'
make: *** [docs] Error 2
```
Please advise!

**Comment by glemaitre** [comment]
You need to install `dateutil` apparently.
